spring.application.name: buyer
server.port: 8088
#store:
#  ribbon:
#    listOfServers: 172.16.14.68:8080
#ribbon:
#  eureka:
#    enabled: false
spring:
  cloud:
    zookeeper:
      connect-string: 172.16.2.182:2181,172.16.2.183:2181
#      connect-string: 172.16.31.177:2181